Fix typos in rasterize docstrings
rafaqz/Rasters.jl pull request #378
Opened 2023-01-19 21:03 UTC by felixcremer

Fix a few typos and clarify (at least for me) some things in the rasterize docstrings.

2023-01-20 09:15 UTC, felixcremer commented
I do not see, how my docstring changes make an unrelated doctest fail.

2023-01-28 20:48 UTC, rafaqz commented
You didn't I just have to stop testing that

2023-01-28 20:51 UTC, rafaqz requested changes

2023-01-28 20:51 UTC, rafaqz commented on src/methods/rasterize.jl
> +    or a Tables.jl compatible object containing points and values columns or an `:geometry`.
```suggestion
    or a Tables.jl compatible object containing a `:geometry` column or points and values columns.
```

2023-01-28 20:51 UTC, merged