add possibility to specify crop dimensions
rafaqz/Rasters.jl pull request #539
Opened 2023-10-19 11:04 UTC by maxfreu

This adds the possibility to specify crop dimensions. Hope it looks ok :)

2023-10-19 12:33 UTC, rafaqz requested changes
Lools good

2023-10-19 12:33 UTC, rafaqz commented on src/methods/crop_extend.jl
> +    target_dims = get(kw, :dims, name.(dims(to)))
You can just do this in the keywords directly without `get`, just add a `dims` keyword.

2023-10-19 20:11 UTC, rafaqz commented on src/methods/crop_extend.jl
> +function _crop_to(A, to::RasterStackOrArray; kw...)
```suggestion
function _crop_to(A, to::RasterStackOrArray; dims=dims(to), kw...)
```

2023-10-19 20:12 UTC, rafaqz commented on src/methods/crop_extend.jl
> +    return _crop_to(A, dims(to, target_dims); kw...)
```suggestion
    return _crop_to(A, DD.dims(to, dims); kw...)
```

2023-10-19 20:12 UTC, rafaqz commented on src/methods/crop_extend.jl
> +    target_dims = get(kw, :dims, name.(dims(to)))
```suggestion
```

2023-10-20 16:03 UTC, maxfreu commented
This was a clear case of not seeing the forest for the trees :D I'll fix it!

2023-10-22 07:43 UTC, maxfreu commented
I noticed that there are unused variables in the crop functions, so it's likely that they don't work as you intended:

https://github.com/rafaqz/Rasters.jl/blob/88af714ec6194c321c6d1188e2c38c5e318318cf/src/methods/crop_extend.jl#L98-L100

https://github.com/rafaqz/Rasters.jl/blob/88af714ec6194c321c6d1188e2c38c5e318318cf/src/methods/crop_extend.jl#L104

2023-10-22 09:58 UTC, rafaqz commented
Good cqtch, the second one `ds` is just no longer needed, thats in DD now.

In the first `sampled` should be used instead of `to`. It will mostly just stop bands or other `Categorical` lookups being used to crop.

2023-10-22 11:39 UTC, maxfreu commented
Actually, cropping forward ordered categorical int64 band dimensions worked. But I changed it nevertheless, as there probably will be problems with string values.

2023-10-22 12:21 UTC, rafaqz commented
Yeah the idea was you basically never want to use crop for bands or categorical things, so passing in bands in the `to` template should be ignored

2023-10-22 12:22 UTC, merged